// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniSpaceMapNAU.Infrastructure.Data;

#nullable disable

namespace UniSpaceMapNAU.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240809155618_addStudentGroup")]
    partial class addStudentGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniSpaceMapNAU.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialtyNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacultyId = 1,
                            Name = "Прикладна математика",
                            SpecialtyNumber = 113
                        },
                        new
                        {
                            Id = 2,
                            FacultyId = 1,
                            Name = "Кібербезпека",
                            SpecialtyNumber = 125
                        },
                        new
                        {
                            Id = 3,
                            FacultyId = 1,
                            Name = "Компʼютерні науки",
                            SpecialtyNumber = 122
                        },
                        new
                        {
                            Id = 4,
                            FacultyId = 1,
                            Name = "Компʼютерна інженерія",
                            SpecialtyNumber = 123
                        },
                        new
                        {
                            Id = 5,
                            FacultyId = 1,
                            Name = "Інформаційні системи та технології",
                            SpecialtyNumber = 126
                        });
                });

            modelBuilder.Entity("UniSpaceMapNAU.Domain.Entities.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ФКНТ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ФАЕТ"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ФЕБА"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ФЕБІТ"
                        },
                        new
                        {
                            Id = 5,
                            Name = "АКФ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ФЛСК"
                        },
                        new
                        {
                            Id = 7,
                            Name = "ФМВ"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ФНСА"
                        },
                        new
                        {
                            Id = 9,
                            Name = "ФТМЛ"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ЮФ"
                        });
                });

            modelBuilder.Entity("UniSpaceMapNAU.Domain.Entities.StudentGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentId");

                    b.ToTable("StudentsGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentId = 1,
                            Name = "Group A"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentId = 1,
                            Name = "Group B"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentId = 1,
                            Name = "Group C"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentId = 4,
                            Name = "Group E"
                        });
                });

            modelBuilder.Entity("UniSpaceMapNAU.Domain.Entities.Department", b =>
                {
                    b.HasOne("UniSpaceMapNAU.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("UniSpaceMapNAU.Domain.Entities.StudentGroup", b =>
                {
                    b.HasOne("UniSpaceMapNAU.Domain.Entities.Department", "Departament")
                        .WithMany("StudentGroups")
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("UniSpaceMapNAU.Domain.Entities.Department", b =>
                {
                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("UniSpaceMapNAU.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
